<?php

function provinsi(){
	$array_prov = array(
						'' => 'Pilih Provinsi',
						'aceh' => 'Aceh',
						'bali' => 'Bali',
						'banten' => 'Banten',
						'bengkulu' => 'Bengkulu',
						'gorontalo' => 'Gorontalo',
						'jakarta' => 'Jakarta',
						'jambi' => 'Jambi',
						'jawa_barat' => 'Jawa Barat',
						'jawa_tengah' => 'Jawa Tengah',
						'jawa_timur' => 'Jawa Timur',
						'kalimantan_barat' => 'Kalimantan Barat',
						'kalimantan_selatan' => 'Kalimantan Selatan',
						'kalimantan_tengah' => 'Kalimantan Tengah',
						'kalimantan_timur' => 'Kalimantan Timur',
						'kalimantan_utara' => 'Kalimantan Utara',
						'kepulauan_bangka_belitung' => 'Kepulauan Bangka Belitung',
						'kepulauan_riau' => 'Kepulauan Riau',
						'lampung' => 'Lampung',
						'maluku' => 'Maluku',
						'maluku_utara' => 'Maluku Utara',
						'nusa_tenggara_barat' => 'Nusa Tenggara Barat',
						'nusa_tenggara_timur' => 'Nusa Tenggara Timur',
						'papua' => 'Papua',
						'papua_barat' => 'Papua Barat',
						'riau' => 'Riau',
						'sulawesi_selatan' => 'Sulawesi Selatan',
						'sulawesi_tengah' => 'Sulawesi Tengah',
						'sulawesi_tenggara' => 'Sulawesi Tenggara',
						'sulawesi_utara' => 'Sulawesi Utara',
						'sumatera_barat' => 'Sumatera Barat',
						'sumatera_selatan' => 'Sumatera Selatan',
						'sumatera_utara' => 'Sumatera Utara',
						'yogyakarta' => 'Yogyakarta'
					);
	return $array_prov;	
}

function provinsi_dropdown($selected=''){
	$_this =& get_instance();
	$_this->load->helper('form');
	return form_dropdown('provinsi', provinsi(), '', 'class="formdropdown midlelong" id="provinsi"');
}

function provinsi_kota($key){
	$array_prov_kota = array(
		'aceh' => array(
						'kota_banda_aceh' => 'Kota Banda Aceh',
						'kota_langsa' => 'Kota Langsa',
						'kota_lhokseumawe' => 'Kota Lhokseumawe',
						'kota_sabang' => 'Kota Sabang',
						'kota_subulussalam' => 'Kota Subulussalam',
						'kabupaten_aceh_barat_daya' => 'Kabupaten Aceh Barat Daya',
						'kabupaten_aceh_barat' => 'Kabupaten Aceh Barat',
						'kabupaten_aceh_besar' => 'Kabupaten Aceh Besar',
						'kabupaten_aceh_jaya' => 'Kabupaten Aceh Jaya',
						'kabupaten_aceh_selatan' => 'Kabupaten Aceh Selatan',
						'kabupaten_aceh_singkil' => 'Kabupaten Aceh Singkil',
						'kabupaten_aceh_tamiang' => 'Kabupaten Aceh Tamiang',
						'kabupaten_aceh_tengah' => 'Kabupaten Aceh Tengah',
						'kabupaten_aceh_tenggara' => 'Kabupaten Aceh Tenggara',
						'kabupaten_aceh_timur' => 'Kabupaten Aceh Timur',
						'kabupaten_aceh_utara' => 'Kabupaten Aceh Utara',
						'kabupaten_bener_meriah' => 'Kabupaten Bener Meriah',
						'kabupaten_bireuen' => 'Kabupaten Bireuen',
						'kabupaten_gayo_lues' => 'Kabupaten Gayo Lues',
						'kabupaten_nagan_raya' => 'Kabupaten Nagan Raya',
						'kabupaten_pidie_jaya' => 'Kabupaten Pidie Jaya',
						'kabupaten_pidie' => 'Kabupaten Pidie',
						'kabupaten_simeulue' => 'Kabupaten Simeulue'	
		),

		'bali' => array(
						'kota_denpasar' => 'Kota Denpasar',
						'kabupaten_badung' => 'Kabupaten Badung',
						'kabupaten_bangli' => 'Kabupaten Bangli',
						'kabupaten_buleleng' => 'Kabupaten Buleleng',
						'kabupaten_gianyar' => 'Kabupaten Gianyar',
						'kabupaten_jembrana' => 'Kabupaten Jembrana',
						'kabupaten_karangasem' => 'Kabupaten Karangasem',
						'kabupaten_klungkung' => 'Kabupaten Klungkung',
						'kabupaten_tabanan' => 'Kabupaten Tabanan',
					),

		'banten' => array(
						'kota_cilegon' => 'Kota Cilegon',
						'kota_serang' => 'Kota Serang',
						'kota_tangerang_selatan' => 'Kota Tangerang Selatan',
						'kota_tangerang' => 'Kota Tangerang',
						'kabupaten_lebak' => 'Kabupaten Lebak',
						'kabupaten_pandeglang' => 'Kabupaten Pandeglang',
						'kabupaten_serang' => 'Kabupaten Serang',
						'kabupaten_tangerang' => 'Kabupaten Tangerang',
					),

		'bengkulu' => array(
						'kota_bengkulu' => 'Kota Bengkulu',
						'kabupaten_bengkulu_selatan' => 'Kabupaten Bengkulu Selatan',
						'kabupaten_bengkulu_tengah' => 'Kabupaten Bengkulu Tengah',
						'kabupaten_bengkulu_utara' => 'Kabupaten Bengkulu Utara',
						'kabupaten_kaur' => 'Kabupaten Kaur',
						'kabupaten_kepahiang' => 'Kabupaten Kepahiang',
						'kabupaten_lebong' => 'Kabupaten Lebong',
						'kabupaten_mukomuko' => 'Kabupaten Mukomuko',
						'kabupaten_rejang_lebong' => 'Kabupaten Rejang Lebong',
						'kabupaten_seluma' => 'Kabupaten Seluma',
					),

		'gorontalo' => array(
						'kota_gorontalo' => 'Kota Gorontalo',
						'kabupaten_boalemo' => 'Kabupaten Boalemo',
						'kabupaten_bone_bolango' => 'Kabupaten Bone Bolango',
						'kabupaten_gorontalo_utara' => 'Kabupaten Gorontalo Utara',
						'kabupaten_gorontalo' => 'Kabupaten Gorontalo',
						'kabupaten_pohuwato' => 'Kabupaten Pohuwato',
					),

		'jakarta' => array(
						'kota_administrasi_jakarta_barat' => 'Kota Administrasi Jakarta Barat',
						'kota_administrasi_jakarta_pusat' => 'Kota Administrasi Jakarta Pusat',
						'kota_administrasi_jakarta_selatan' => 'Kota Administrasi Jakarta Selatan',
						'kota_administrasi_jakarta_timur' => 'Kota Administrasi Jakarta Timur',
						'kota_administrasi_jakarta_utara' => 'Kota Administrasi Jakarta Utara',
						'kabupaten_administrasi_kepulauan_seribu' => 'Kabupaten Administrasi Kepulauan Seribu',
					),

		'jambi' => array(
						'kota_jambi' => 'Kota Jambi',
						'kota_sungai_penuh' => 'Kota Sungai Penuh',
						'kabupaten_batanghari' => 'Kabupaten Batanghari',
						'kabupaten_bungo' => 'Kabupaten Bungo',
						'kabupaten_kerinci' => 'Kabupaten Kerinci',
						'kabupaten_merangin' => 'Kabupaten Merangin',
						'kabupaten_muaro_jambi' => 'Kabupaten Muaro Jambi',
						'kabupaten_sarolangun' => 'Kabupaten Sarolangun',
						'kabupaten_tanjung_jabung_barat' => 'Kabupaten Tanjung Jabung Barat',
						'kabupaten_tanjung_jabung_timur' => 'Kabupaten Tanjung Jabung Timur',
						'kabupaten_tebo' => 'Kabupaten Tebo',
					),

		'jawa_barat' => array(
					'kota_bandung' => 'Kota Bandung',
					'kota_banjar' => 'Kota Banjar',
					'kota_bekasi' => 'Kota Bekasi',
					'kota_bogor' => 'Kota Bogor',
					'kota_cimahi' => 'Kota Cimahi',
					'kota_cirebon' => 'Kota Cirebon',
					'kota_depok' => 'Kota Depok',
					'kota_sukabumi' => 'Kota Sukabumi',
					'kota_tasikmalaya' => 'Kota Tasikmalaya',
					'kabupaten_bandung_barat' => 'Kabupaten Bandung Barat',
					'kabupaten_bandung' => 'Kabupaten Bandung',
					'kabupaten_bekasi' => 'Kabupaten Bekasi',
					'kabupaten_bogor' => 'Kabupaten Bogor',
					'kabupaten_ciamis' => 'Kabupaten Ciamis',
					'kabupaten_cianjur' => 'Kabupaten Cianjur',
					'kabupaten_cirebon' => 'Kabupaten Cirebon',
					'kabupaten_garut' => 'Kabupaten Garut',
					'kabupaten_indramayu' => 'Kabupaten Indramayu',
					'kabupaten_karawang' => 'Kabupaten Karawang',
					'kabupaten_kuningan' => 'Kabupaten Kuningan',
					'kabupaten_majalengka' => 'Kabupaten Majalengka',
					'kabupaten_majalengka' => 'Kabupaten Majalengka',
					'kabupaten_purwakarta' => 'Kabupaten Purwakarta',
					'kabupaten_subang' => 'Kabupaten Subang',
					'kabupaten_sukabumi' => 'Kabupaten Sukabumi',
					'kabupaten_sumedang' => 'Kabupaten Sumedang',
					'kabupaten_tasikmalaya' => 'Kabupaten Tasikmalaya',
				),

		'jawa_tengah' => array(
					'kota_magelang' => 'Kota Magelang',
					'kota_pekalongan' => 'Kota Pekalongan',
					'kota_salatiga' => 'Kota Salatiga',
					'kota_semarang' => 'Kota Semarang',
					'kota_surakarta' => 'Kota Surakarta',
					'kota_tegal' => 'Kota Tegal',
					'kabupaten_banjarnegara' => 'Kabupaten Banjarnegara',
					'kabupaten_banyumas' => 'Kabupaten Banyumas',
					'kabupaten_batang' => 'Kabupaten Batang',
					'kabupaten_blora' => 'Kabupaten Blora',
					'kabupaten_boyolali' => 'Kabupaten Boyolali',
					'kabupaten_brebes' => 'Kabupaten Brebes',
					'kabupaten_cilacap' => 'Kabupaten Cilacap',
					'kabupaten_demak' => 'Kabupaten Demak',
					'kabupaten_grobogan' => 'Kabupaten Grobogan',
					'kabupaten_jepara' => 'Kabupaten Jepara',
					'kabupaten_karanganyar' => 'Kabupaten Karanganyar',
					'kabupaten_kebumen' => 'Kabupaten Kebumen',
					'kabupaten_kendal' => 'Kabupaten Kendal',
					'kabupaten_klaten' => 'Kabupaten Klaten',
					'kabupaten_kudus' => 'Kabupaten Kudus',
					'kabupaten_magelang' => 'Kabupaten Magelang',
					'kabupaten_pati' => 'Kabupaten Pati',
					'kabupaten_pekalongan' => 'Kabupaten Pekalongan',
					'kabupaten_pemalang' => 'Kabupaten Pemalang',
					'kabupaten_purbalingga' => 'Kabupaten Purbalingga',
					'kabupaten_purworejo' => 'Kabupaten Purworejo',
					'kabupaten_rembang' => 'Kabupaten Rembang',
					'kabupaten_semarang' => 'Kabupaten Semarang',
					'kabupaten_sragen' => 'Kabupaten Sragen',
					'kabupaten_sukoharjo' => 'Kabupaten Sukoharjo',
					'kabupaten_tegal' => 'Kabupaten Tegal',
					'kabupaten_temanggung' => 'Kabupaten Temanggung',
					'kabupaten_wonogiri' => 'Kabupaten Wonogiri',
					'kabupaten_wonosobo' => 'Kabupaten Wonosobo',
				),

		'jawa_timur' => array(
					'kota_batu' => 'Kota Batu',
					'kota_blitar' => 'Kota Blitar',
					'kota_kediri' => 'Kota Kediri',
					'kota_madiun' => 'Kota Madiun',
					'kota_malang' => 'Kota Malang',
					'kota_mojokerto' => 'Kota Mojokerto',
					'kota_pasuruan' => 'Kota Pasuruan',
					'kota_probolinggo' => 'Kota Probolinggo',
					'kota_surabaya' => 'Kota Surabaya',
					'kabupaten_bangkalan' => 'Kabupaten Bangkalan',
					'kabupaten_banyuwangi' => 'Kabupaten Banyuwangi',
					'kabupaten_blitar' => 'Kabupaten Blitar',
					'kabupaten_bojonegoro' => 'Kabupaten Bojonegoro',
					'kabupaten_bondowoso' => 'Kabupaten Bondowoso',
					'kabupaten_gresik' => 'Kabupaten Gresik',
					'kabupaten_jember' => 'Kabupaten Jember',
					'kabupaten_jombang' => 'Kabupaten Jombang',
					'kabupaten_kediri' => 'Kabupaten Kediri',
					'kabupaten_lamongan' => 'Kabupaten Lamongan',
					'kabupaten_lumajang' => 'Kabupaten Lumajang',
					'kabupaten_madiun' => 'Kabupaten Madiun',
					'kabupaten_malang' => 'Kabupaten Malang',
					'kabupaten_mojokerto' => 'Kabupaten Mojokerto',
					'kabupaten_nganjuk' => 'Kabupaten Nganjuk',
					'kabupaten_ngawi' => 'Kabupaten Ngawi',
					'kabupaten_pacitan' => 'Kabupaten Pacitan',
					'kabupaten_pamekasan' => 'Kabupaten Pamekasan',
					'kabupaten_pasuruan' => 'Kabupaten Pasuruan',
					'kabupaten_ponorogo' => 'Kabupaten Ponorogo',
					'kabupaten_probolinggo' => 'Kabupaten Probolinggo',
					'kabupaten_sampang' => 'Kabupaten Sampang',
					'kabupaten_sidoarjo' => 'Kabupaten Sidoarjo',
					'kabupaten_situbondo' => 'Kabupaten Situbondo',
					'kabupaten_sumenep' => 'Kabupaten Sumenep',
					'kabupaten_trenggalek' => 'Kabupaten Trenggalek',
					'kabupaten_tuban' => 'Kabupaten Tuban',
					'kabupaten_tulungagung' => 'Kabupaten Tulungagung',

				),

		'kalimantan_barat' => array(
					'kota_pontianak' => 'Kota Pontianak',
					'kota_singkawang' => 'Kota Singkawang',
					'kabupaten_bengkayang' => 'Kabupaten Bengkayang',
					'kabupaten_kapuas_hulu' => 'Kabupaten Kapuas Hulu',
					'kabupaten_kayong_utara' => 'Kabupaten Kayong Utara',
					'kabupaten_ketapang' => 'Kabupaten Ketapang',
					'kabupaten_kubu_raya' => 'Kabupaten Kubu Raya',
					'kabupaten_landak' => 'Kabupaten Landak',
					'kabupaten_melawi' => 'Kabupaten Melawi',
					'kabupaten_pontianak' => 'Kabupaten Pontianak',
					'kabupaten_sambas' => 'Kabupaten Sambas',
					'kabupaten_sanggau' => 'Kabupaten Sanggau',
					'kabupaten_sekadau' => 'Kabupaten Sekadau',
					'kabupaten_sintang' => 'Kabupaten Sintang',
				),

		'kalimantan_selatan' => array(
					'kota_banjarbaru' => 'Kota Banjarbaru',
					'kota_banjarmasin' => 'Kota Banjarmasin',
					'kabupaten_balangan' => 'Kabupaten Balangan',
					'kabupaten_banjar' => 'Kabupaten Banjar',
					'kabupaten_barito_kuala' => 'Kabupaten Barito Kuala',
					'kabupaten_hulu_sungai_selatan' => 'Kabupaten Hulu Sungai Selatan',
					'kabupaten_hulu_sungai_tengah' => 'Kabupaten Hulu Sungai Tengah',
					'kabupaten_hulu_sungai_utara' => 'Kabupaten Hulu Sungai Utara',
					'kabupaten_kotabaru' => 'Kabupaten Kotabaru',
					'kabupaten_tabalong' => 'Kabupaten Tabalong',
					'kabupaten_tanah_bumbu' => 'Kabupaten Tanah Bumbu',
					'kabupaten_tanah_laut' => 'Kabupaten Tanah Laut',
					'kabupaten_tapin' => 'Kabupaten Tapin',
				),

		'kalimantan_tengah' => array(
					'kota_palangka_raya' => 'Kota Palangka Raya',
					'kabupaten_barito_selatan' => 'Kabupaten Barito Selatan',
					'kabupaten_barito_timur' => 'Kabupaten Barito Timur',
					'kabupaten_barito_utara' => 'Kabupaten Barito Utara',
					'kabupaten_gunung_mas' => 'Kabupaten Gunung Mas',
					'kabupaten_kapuas' => 'Kabupaten Kapuas',
					'kabupaten_katingan' => 'Kabupaten Katingan',
					'kabupaten_kotawaringin_barat' => 'Kabupaten Kotawaringin Barat',
					'kabupaten_kotawaringin_timur' => 'Kabupaten Kotawaringin Timur',
					'kabupaten_lamandau' => 'Kabupaten Lamandau',
					'kabupaten_murung_raya' => 'Kabupaten Murung Raya',
					'kabupaten_pulang_pisau' => 'Kabupaten Pulang Pisau',
					'kabupaten_seruyan' => 'Kabupaten Seruyan',
					'kabupaten_sukamara' => 'Kabupaten Sukamara',
				),

		'kalimantan_timur' => array(
					'kota_balikpapan' => 'Kota Balikpapan',
					'kota_bontang' => 'Kota Bontang',
					'kota_samarinda' => 'Kota Samarinda',
					'kabupaten_berau' => 'Kabupaten Berau',
					'kabupaten_kutai_barat' => 'Kabupaten Kutai Barat',
					'kabupaten_kutai_kartanegara' => 'Kabupaten Kutai Kartanegara',
					'kabupaten_kutai_timur' => 'Kabupaten Kutai Timur',
					'kabupaten_mahakam_ulu' => 'Kabupaten Mahakam Ulu',
					'kabupaten_paser' => 'Kabupaten Paser',
					'kabupaten_penajam_paser_utara' => 'Kabupaten Penajam Paser Utara',
				),

		'kalimantan_utara' => array(
					'kota_tarakan' => 'Kota Tarakan',
					'kabupaten_bulungan' => 'Kabupaten Bulungan',
					'kabupaten_malinau' => 'Kabupaten Malinau',
					'kabupaten_nunukan' => 'Kabupaten Nunukan',
					'kabupaten_tana_tidung' => 'Kabupaten Tana Tidung',
				),

		'kepulauan_bangka_belitung' => array(
					'kota_pangkal_pinang' => 'Kota Pangkal Pinang',
					'kabupaten_bangka_barat' => 'Kabupaten Bangka Barat',
					'kabupaten_bangka_selatan' => 'Kabupaten Bangka Selatan',
					'kabupaten_bangka_tengah' => 'Kabupaten Bangka Tengah',
					'kabupaten_bangka' => 'Kabupaten Bangka',
					'kabupaten_belitung_timur' => 'Kabupaten Belitung Timur',
					'kabupaten_belitung' => 'Kabupaten Belitung',
				),

		'kepulauan_riau' => array(
					'kota_batam' => 'Kota Batam',
					'kota_tanjung_pinang' => 'Kota Tanjung Pinang',
					'kabupaten_bintan' => 'Kabupaten Bintan',
					'kabupaten_karimun' => 'Kabupaten Karimun',
					'kabupaten_kepulauan_anambas' => 'Kabupaten Kepulauan Anambas',
					'kabupaten_lingga' => 'Kabupaten Lingga',
					'kabupaten_natuna' => 'Kabupaten Natuna',
				),

		'lampung' => array(
					'kota_bandar_lampung' => 'Kota Bandar Lampung',
					'kota_metro' => 'Kota Metro',
					'kabupaten_lampung_barat' => 'Kabupaten Lampung Barat',
					'kabupaten_lampung_selatan' => 'Kabupaten Lampung Selatan',
					'kabupaten_lampung_tengah' => 'Kabupaten Lampung Tengah',
					'kabupaten_lampung_timur' => 'Kabupaten Lampung Timur',
					'kabupaten_lampung_utara' => 'Kabupaten Lampung Utara',
					'kabupaten_mesuji' => 'Kabupaten Mesuji',
					'kabupaten_pesawaran' => 'Kabupaten Pesawaran',
					'kabupaten_pringsewu' => 'Kabupaten Pringsewu',
					'kabupaten_tanggamus' => 'Kabupaten Tanggamus',
					'kabupaten_tulang_bawang_barat' => 'Kabupaten Tulang Bawang Barat',
					'kabupaten_tulang_bawang' => 'Kabupaten Tulang Bawang',
					'kabupaten_way_kanan' => 'Kabupaten Way Kanan',
				),

		'maluku' => array(
					'kota_ambon' => 'Kota Ambon',
					'kota_tual' => 'Kota Tual',
					'kabupaten_buru_selatan' => 'Kabupaten Buru Selatan',
					'kabupaten_buru' => 'Kabupaten Buru',
					'kabupaten_kepulauan_aru' => 'Kabupaten Kepulauan Aru',
					'kabupaten_maluku_barat_daya' => 'Kabupaten Maluku Barat Daya',
					'kabupaten_maluku_tengah' => 'Kabupaten Maluku Tengah',
					'kabupaten_maluku_tenggara_barat' => 'Kabupaten Maluku Tenggara Barat',
					'kabupaten_maluku_tenggara' => 'Kabupaten Maluku Tenggara',
					'kabupaten_seram_bagian_barat' => 'Kabupaten Seram Bagian Barat',
					'kabupaten_seram_bagian_timur' => 'Kabupaten Seram Bagian Timur',
				),

		'maluku_utara' => array(
					'Kota Ternate' => 'Kota Ternate',
					'Kota Tidore Kepulauan' => 'Kota Tidore Kepulauan',
					'Kabupaten Halmahera Barat' => 'Kabupaten Halmahera Barat',
					'Kabupaten Halmahera Selatan' => 'Kabupaten Halmahera Selatan',
					'Kabupaten Halmahera Tengah' => 'Kabupaten Halmahera Tengah',
					'Kabupaten Halmahera Timur' => 'Kabupaten Halmahera Timur',
					'Kabupaten Halmahera Utara' => 'Kabupaten Halmahera Utara',
					'Kabupaten Kepulauan Sula' => 'Kabupaten Kepulauan Sula',
					'Kabupaten Pulau Morotai' => 'Kabupaten Pulau Morotai',
				),

		'nusa_tenggara_barat' => array(
					'Kota Bima' => 'Kota Bima',
					'Kota Mataram' => 'Kota Mataram',
					'Kabupaten Bima' => 'Kabupaten Bima',
					'Kabupaten Dompu' => 'Kabupaten Dompu',
					'Kabupaten Lombok Barat' => 'Kabupaten Lombok Barat',
					'Kabupaten Lombok Tengah' => 'Kabupaten Lombok Tengah',
					'Kabupaten Lombok Timur' => 'Kabupaten Lombok Timur',
					'Kabupaten Lombok Utara' => 'Kabupaten Lombok Utara',
					'Kabupaten Sumbawa Barat' => 'Kabupaten Sumbawa Barat',
					'Kabupaten Sumbawa' => 'Kabupaten Sumbawa',
				),

		'nusa_tenggara_timur' => array(
					'kota_kupang' => 'Kota Kupang',
					'kabupaten_alor' => 'Kabupaten Alor',
					'kabupaten_belu' => 'Kabupaten Belu',
					'kabupaten_ende' => 'Kabupaten Ende',
					'kabupaten_flores_timur' => 'Kabupaten Flores Timur',
					'kabupaten_kupang' => 'Kabupaten Kupang',
					'kabupaten_lembata' => 'Kabupaten Lembata',
					'kabupaten_manggarai_barat' => 'Kabupaten Manggarai Barat',
					'kabupaten_manggarai_timur' => 'Kabupaten Manggarai Timur',
					'kabupaten_manggarai' => 'Kabupaten Manggarai',
					'kabupaten_nagekeo' => 'Kabupaten Nagekeo',
					'kabupaten_ngada' => 'Kabupaten Ngada',
					'kabupaten_rote_ndao' => 'Kabupaten Rote Ndao',
					'kabupaten_sabu_raijua' => 'Kabupaten Sabu Raijua',
					'kabupaten_sikka' => 'Kabupaten Sikka',
					'kabupaten_sumba_barat_daya' => 'Kabupaten Sumba Barat Daya',
					'kabupaten_sumba_barat' => 'Kabupaten Sumba Barat',
					'kabupaten_sumba_tengah' => 'Kabupaten Sumba Tengah',
					'kabupaten_sumba_timur' => 'Kabupaten Sumba Timur',
					'kabupaten_timor_tengah_selatan' => 'Kabupaten Timor Tengah Selatan',
					'kabupaten_timor_tengah_utara' => 'Kabupaten Timor Tengah Utara',
				),

		'papua' => array(
					'kota_jayapura' => 'Kota Jayapura',
					'kabupaten_asmat' => 'Kabupaten Asmat',
					'kabupaten_biak_numfor' => 'Kabupaten Biak Numfor',
					'kabupaten_boven_digoel' => 'Kabupaten Boven Digoel',
					'kabupaten_deiyai' => 'Kabupaten Deiyai',
					'kabupaten_dogiyai' => 'Kabupaten Dogiyai',
					'kabupaten_intan_jaya' => 'Kabupaten Intan Jaya',
					'kabupaten_jayapura' => 'Kabupaten Jayapura',
					'kabupaten_jayawijaya' => 'Kabupaten Jayawijaya',
					'kabupaten_keerom' => 'Kabupaten Keerom',
					'kabupaten_kepulauan_yapen' => 'Kabupaten Kepulauan Yapen',
					'kabupaten_lanny_jaya' => 'Kabupaten Lanny Jaya',
					'kabupaten_mamberamo_raya' => 'Kabupaten Mamberamo Raya',
					'kabupaten_mamberamo_tengah' => 'Kabupaten Mamberamo Tengah',
					'kabupaten_mappi' => 'Kabupaten Mappi',
					'kabupaten_merauke' => 'Kabupaten Merauke',
					'kabupaten_mimika' => 'Kabupaten Mimika',
					'kabupaten_nabire' => 'Kabupaten Nabire',
					'kabupaten_nduga' => 'Kabupaten Nduga',
					'kabupaten_paniai' => 'Kabupaten Paniai',
					'kabupaten_pegunungan_bintang' => 'Kabupaten Pegunungan Bintang',
					'kabupaten_puncak_jaya' => 'Kabupaten Puncak Jaya',
					'kabupaten_puncak' => 'Kabupaten Puncak',
					'kabupaten_sarmi' => 'Kabupaten Sarmi',
					'kabupaten_supiori' => 'Kabupaten Supiori',
					'kabupaten_tolikara' => 'Kabupaten Tolikara',
					'kabupaten_waropen' => 'Kabupaten Waropen',
					'kabupaten_yahukimo' => 'Kabupaten Yahukimo',
					'kabupaten_yalimo' => 'Kabupaten Yalimo',

				),

		'papua_barat' => array(
					'kota_sorong' => 'Kota Sorong',
					'kabupaten_fakfak' => 'Kabupaten Fakfak',
					'kabupaten_kaimana' => 'Kabupaten Kaimana',
					'kabupaten_manokwari' => 'Kabupaten Manokwari',
					'kabupaten_maybrat' => 'Kabupaten Maybrat',
					'kabupaten_raja_ampat' => 'Kabupaten Raja Ampat',
					'kabupaten_sorong_selatan' => 'Kabupaten Sorong Selatan',
					'kabupaten_sorong' => 'Kabupaten Sorong',
					'kabupaten_tambrauw' => 'Kabupaten Tambrauw',
					'kabupaten_teluk_bintuni' => 'Kabupaten Teluk Bintuni',
					'kabupaten_teluk_wondama' => 'Kabupaten Teluk Wondama',
				),

		'riau' => array(
					'kota_dumai' => 'Kota Dumai',
					'kota_pekanbaru' => 'Kota Pekanbaru',
					'kabupaten_bengkalis' => 'Kabupaten Bengkalis',
					'kabupaten_indragiri_hilir' => 'Kabupaten Indragiri Hilir',
					'kabupaten_indragiri_hulu' => 'Kabupaten Indragiri Hulu',
					'kabupaten_kampar' => 'Kabupaten Kampar',
					'kabupaten_kepulauan_meranti' => 'Kabupaten Kepulauan Meranti',
					'kabupaten_kuantan_singingi' => 'Kabupaten Kuantan Singingi',
					'kabupaten_pelalawan' => 'Kabupaten Pelalawan',
					'kabupaten_rokan_hilir' => 'Kabupaten Rokan Hilir',
					'kabupaten_rokan_hulu' => 'Kabupaten Rokan Hulu',
					'kabupaten_siak' => 'Kabupaten Siak',
				),

		'sulawesi_selatan' => array(
					'kota_makassar' => 'Kota Makassar',
					'kota_palopo' => 'Kota Palopo',
					'kota_parepare' => 'Kota Parepare',
					'kabupaten_bantaeng' => 'Kabupaten Bantaeng',
					'kabupaten_barru' => 'Kabupaten Barru',
					'kabupaten_bone' => 'Kabupaten Bone',
					'kabupaten_bulukumba' => 'Kabupaten Bulukumba',
					'kabupaten_enrekang' => 'Kabupaten Enrekang',
					'kabupaten_gowa' => 'Kabupaten Gowa',
					'kabupaten_jeneponto' => 'Kabupaten Jeneponto',
					'kabupaten_kepulauan_selayar' => 'Kabupaten Kepulauan Selayar',
					'kabupaten_luwu_timur' => 'Kabupaten Luwu Timur',
					'kabupaten_luwu_utara' => 'Kabupaten Luwu Utara',
					'kabupaten_luwu' => 'Kabupaten Luwu',
					'kabupaten_maros' => 'Kabupaten Maros',
					'kabupaten_pangkajene_dan_kepulauan' => 'Kabupaten Pangkajene dan Kepulauan',
					'kabupaten_pinrang' => 'Kabupaten Pinrang',
					'kabupaten_sidenreng_rappang' => 'Kabupaten Sidenreng Rappang',
					'kabupaten_sinjai' => 'Kabupaten Sinjai',
					'kabupaten_soppeng' => 'Kabupaten Soppeng',
					'kabupaten_takalar' => 'Kabupaten Takalar',
					'kabupaten_tana_toraja' => 'Kabupaten Tana Toraja',
					'kabupaten_toraja_utara' => 'Kabupaten Toraja Utara',
					'kabupaten_wajo' => 'Kabupaten Wajo',
				),

		'sulawesi_tengah' => array(
					'kota_palu' => 'Kota Palu',
					'kabupaten_banggai_kepulauan' => 'Kabupaten Banggai Kepulauan',
					'kabupaten_banggai' => 'Kabupaten Banggai',
					'kabupaten_buol' => 'Kabupaten Buol',
					'kabupaten_donggala' => 'Kabupaten Donggala',
					'kabupaten_morowali' => 'Kabupaten Morowali',
					'kabupaten_parigi_moutong' => 'Kabupaten Parigi Moutong',
					'kabupaten_poso' => 'Kabupaten Poso',
					'kabupaten_sigi' => 'Kabupaten Sigi',
					'kabupaten_tojo_una-una' => 'Kabupaten Tojo Una-Una',
					'kabupaten_toli-toli' => 'Kabupaten Toli-Toli',
				),

		'sulawesi_tenggara' => array(
					'kota_bau-bau' => 'Kota Bau-Bau',
					'kota_kendari' => 'Kota Kendari',
					'kabupaten_bombana' => 'Kabupaten Bombana',
					'kabupaten_buton_utara' => 'Kabupaten Buton Utara',
					'kabupaten_buton' => 'Kabupaten Buton',
					'kabupaten_kolaka_utara' => 'Kabupaten Kolaka Utara',
					'kabupaten_kolaka' => 'Kabupaten Kolaka',
					'kabupaten_konawe_selatan' => 'Kabupaten Konawe Selatan',
					'kabupaten_konawe_utara' => 'Kabupaten Konawe Utara',
					'kabupaten_konawe' => 'Kabupaten Konawe',
					'kabupaten_muna' => 'Kabupaten Muna',
					'kabupaten_wakatobi' => 'Kabupaten Wakatobi',
				),

		'sulawesi_utara' => array(
					'kota_bitung' => 'Kota Bitung',
					'kota_kotamobagu' => 'Kota Kotamobagu',
					'kota_manado' => 'Kota Manado',
					'kota_tomohon' => 'Kota Tomohon',
					'kabupaten_bolaang_mongondow_selatan' => 'Kabupaten Bolaang Mongondow Selatan',
					'kabupaten_bolaang_mongondow_timur' => 'Kabupaten Bolaang Mongondow Timur',
					'kabupaten_bolaang_mongondow_utara' => 'Kabupaten Bolaang Mongondow Utara',
					'kabupaten_bolaang_mongondow' => 'Kabupaten Bolaang Mongondow',
					'kabupaten_kepulauan_sangihe' => 'Kabupaten Kepulauan Sangihe',
					'kabupaten_kepulauan_siau_tagulandang_biaro' => 'Kabupaten Kepulauan Siau Tagulandang Biaro',
					'kabupaten_kepulauan_talaud' => 'Kabupaten Kepulauan Talaud',
					'kabupaten_minahasa_selatan' => 'Kabupaten Minahasa Selatan',
					'kabupaten_minahasa_tenggara' => 'Kabupaten Minahasa Tenggara',
					'kabupaten_minahasa_utara' => 'Kabupaten Minahasa Utara',
					'kabupaten_minahasa' => 'Kabupaten Minahasa',
				),

		'sumatera_barat' => array(
					'kota_bukittinggi' => 'Kota Bukittinggi',
					'kota_padang' => 'Kota Padang',
					'kota_padangpanjang' => 'Kota Padangpanjang',
					'kota_pariaman' => 'Kota Pariaman',
					'kota_payakumbuh' => 'Kota Payakumbuh',
					'kota_sawahlunto' => 'Kota Sawahlunto',
					'kota_solok' => 'Kota Solok',
					'kabupaten_agam' => 'Kabupaten Agam',
					'kabupaten_dharmasraya' => 'Kabupaten Dharmasraya',
					'kabupaten_kepulauan_mentawai' => 'Kabupaten Kepulauan Mentawai',
					'kabupaten_lima_puluh_kota' => 'Kabupaten Lima Puluh Kota',
					'kabupaten_padang_pariaman' => 'Kabupaten Padang Pariaman',
					'kabupaten_pasaman_barat' => 'Kabupaten Pasaman Barat',
					'kabupaten_pasaman' => 'Kabupaten Pasaman',
					'kabupaten_pesisir_selatan' => 'Kabupaten Pesisir Selatan',
					'kabupaten_sijunjung' => 'Kabupaten Sijunjung',
					'kabupaten_solok_selatan' => 'Kabupaten Solok Selatan',
					'kabupaten_solok' => 'Kabupaten Solok',
					'kabupaten_tanah_datar' => 'Kabupaten Tanah Datar',
				),

		'sumatera_selatan' => array(
					'kota_lubuklinggau' => 'Kota Lubuklinggau',
					'kota_pagar_alam' => 'Kota Pagar Alam',
					'kota_palembang' => 'Kota Palembang',
					'kota_prabumulih' => 'Kota Prabumulih',
					'kabupaten_banyuasin' => 'Kabupaten Banyuasin',
					'kabupaten_empat_lawang' => 'Kabupaten Empat Lawang',
					'kabupaten_lahat' => 'Kabupaten Lahat',
					'kabupaten_muara_enim' => 'Kabupaten Muara Enim',
					'kabupaten_musi_banyuasin' => 'Kabupaten Musi Banyuasin',
					'kabupaten_musi_rawas' => 'Kabupaten Musi Rawas',
					'kabupaten_ogan_ilir' => 'Kabupaten Ogan Ilir',
					'kabupaten_ogan_komering_ilir' => 'Kabupaten Ogan Komering Ilir',
					'kabupaten_ogan_komering_ulu_selatan' => 'Kabupaten Ogan Komering Ulu Selatan',
					'kabupaten_ogan_komering_ulu_timur' => 'Kabupaten Ogan Komering Ulu Timur',
					'kabupaten_ogan_komering_ulu' => 'Kabupaten Ogan Komering Ulu',
				),

		'sumatera_utara' => array(
					'kota_binjai' => 'Kota Binjai',
					'kota_gunungsitoli' => 'Kota Gunungsitoli',
					'kota_medan' => 'Kota Medan',
					'kota_padangsidempuan' => 'Kota Padangsidempuan',
					'kota_pematangsiantar' => 'Kota Pematangsiantar',
					'kota_sibolga' => 'Kota Sibolga',
					'kota_tanjungbalai' => 'Kota Tanjungbalai',
					'kota_tebing_tinggi' => 'Kota Tebing Tinggi',
					'kabupaten_asahan' => 'Kabupaten Asahan',
					'kabupaten_batubara' => 'Kabupaten Batubara',
					'kabupaten_dairi' => 'Kabupaten Dairi',
					'kabupaten_deli_serdang' => 'Kabupaten Deli Serdang',
					'kabupaten_humbang_hasundutan' => 'Kabupaten Humbang Hasundutan',
					'kabupaten_karo' => 'Kabupaten Karo',
					'kabupaten_labuhanbatu_selatan' => 'Kabupaten Labuhanbatu Selatan',
					'kabupaten_labuhanbatu_utara' => 'Kabupaten Labuhanbatu Utara',
					'kabupaten_labuhanbatu' => 'Kabupaten Labuhanbatu',
					'kabupaten_langkat' => 'Kabupaten Langkat',
					'kabupaten_mandailing_natal' => 'Kabupaten Mandailing Natal',
					'kabupaten_nias_barat' => 'Kabupaten Nias Barat',
					'kabupaten_nias_selatan' => 'Kabupaten Nias Selatan',
					'kabupaten_nias_utara' => 'Kabupaten Nias Utara',
					'kabupaten_nias' => 'Kabupaten Nias',
					'kabupaten_padang_lawas_utara' => 'Kabupaten Padang Lawas Utara',
					'kabupaten_padang_lawas' => 'Kabupaten Padang Lawas',
					'kabupaten_pakpak_bharat' => 'Kabupaten Pakpak Bharat',
					'kabupaten_samosir' => 'Kabupaten Samosir',
					'kabupaten_serdang_bedagai' => 'Kabupaten Serdang Bedagai',
					'kabupaten_simalungun' => 'Kabupaten Simalungun',
					'kabupaten_tapanuli_selatan' => 'Kabupaten Tapanuli Selatan',
					'kabupaten_tapanuli_tengah' => 'Kabupaten Tapanuli Tengah',
					'kabupaten_tapanuli_utara' => 'Kabupaten Tapanuli Utara',
					'kabupaten_toba_samosir' => 'Kabupaten Toba Samosir',
				),

		'yogyakarta' => array(
					'kota_yogyakarta' => 'Kota Yogyakarta',
					'kabupaten_bantul' => 'Kabupaten Bantul',
					'kabupaten_gunung_kidul' => 'Kabupaten Gunung Kidul',
					'kabupaten_kulon_progo' => 'Kabupaten Kulon Progo',
					'kabupaten_sleman' => 'Kabupaten Sleman',
				),
	);	
	
	return $array_prov_kota[$key];
}

function provinsi_kota_dropdown(){
	$arrayprov = array('Pilih kota/kabupaten');
	return form_dropdown('provinsi_kota',$arrayprov,'','class="formdropdown midlelong" id="provinsi_kota"');
}


?>